branches:
  only:
    - master

jobs:
  include:
    - stage: test
      name: "Unit Tests: Java 8"
      language: java
      dist: trusty
      jdk:
        - oraclejdk8
      before_install:
        - cd nifi-ngsi-bundle
      install:
        - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -Padd-dependencies-for-IDEA
      before_script:
        - mvn verify -Padd-dependencies-for-IDEA  
      script:
        - mvn clean test -Dtest=Test* cobertura:cobertura coveralls:report -Padd-dependencies-for-IDEA -DCOVERALLS_TOKEN=$COVERALLS_TOKEN
      after_success:
        - cd ../..
        - mvn clean cobertura:cobertura coveralls:report

    - stage: test
      name: "Documentation Tests"
      language: node_js
      node_js:
        - "10"
      install:
        - npm install
      script:
        - npm run lint:md
        #- npm run lint:text
