site_name: fiware-draco
site_url: https://fiware-draco.readthedocs.org
repo_url: https://github.com/ging/fiware-draco.git
site_description: Draco Documentation
docs_dir: docs
site_dir: html
markdown_extensions: [toc,fenced_code]
use_directory_urls: false
theme: readthedocs
extra_css: ["https://www.fiware.org/style/fiware_readthedocs.css", "https://www.fiware.org/style/fiware_readthedocs_core.css"]
google_analytics: ['UA-83727401-6', 'fiware-draco.readthedocs.io']
pages:
  - Home: index.md
  - 'Quick Start Guide': quick_start_guide.md
  - 'Installation and Administration Guide':
      - 'Introduction': 'installation_and_administration_guide/introduction.md'
      - 'Installation via RPM': 'installation_and_administration_guide/install_with_rpm.md'
      - 'Installation from sources': 'installation_and_administration_guide/install_from_sources.md'
      - 'Installation via docker': 'installation_and_administration_guide/install_with_docker.md'
      - 'Draco GUI': 'installation_and_administration_guide/draco_gui.md'
      - 'Processors configuration': 'installation_and_administration_guide/processors_configuration.md'
      - 'Controllers configuration': 'installation_and_administration_guide/controllers_configuration.md'
      - 'Connection Components': 'installation_and_administration_guide/connection_components.md'
      - 'Templates': 'installation_and_administration_guide/templates-draco.md'
      - 'REST API': 'installation_and_administration_guide/rest_api.md'
      - 'Issues and Contact': 'installation_and_administration_guide/issues_and_contact.md'
  - 'Processors catalogue':
      - 'Introduction': 'processors_catalogue/introduction.md'
      - 'MongoDB backend': 'processors_catalogue/ngsi_mongo_sink.md'
      - 'MySQL backend': 'processors_catalogue/ngsi_mysql_sink.md'
      - 'PostgreSQL backend': 'processors_catalogue/ngsi_postgresql_sink.md'
      - 'CKAN backend': 'processors_catalogue/ngsi_ckan_sink.md'
      - 'Carto backend': 'processors_catalogue/ngsi_carto_sink.md'
      - 'Cassandra backend': 'processors_catalogue/ngsi_cassandra_sink.md'
      - 'HDFS backend': 'processors_catalogue/ngsi_hdfs_sink.md'
      - 'Update CKAN Metadata backend': 'processors_catalogue/update_ckan_metadata.md'
      - 'REST Handler': 'processors_catalogue/ngsi_rest_handler.md'
      - 'Issues and Contact': 'processors_catalogue/issues_and_contact.md'
  - 'Roadmap': roadmap.md
